<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>..\..\..\Bin\$(Configuration)X64\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Probe.cs" />
    <ProjectReference Include="..\..\..\Nuclear.ScriptCore\Nuclear.ScriptCore.csproj" />
  </ItemGroup>
</Project>
