image: Visual Studio 2017
platform:
  - X64

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive

  - RunCmakeForDependencies.bat
  
  # Build projects that only matter
  - ps: msbuild External\CmakeProjects\GLFW\src\glfw.vcxproj /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
  - ps: msbuild External\CmakeProjects\Diligent\Project.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
  - ps: msbuild External\CmakeProjects\Assimp\Assimp.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
 
  - CopyDependenciesBinaries.bat
  
build:
  parallel: true                  # enable MSBuild parallel builds
  verbosity: minimal
  project: Nuclear Engine.sln