image: Visual Studio 2017
platform:
  - X64

configuration:
  - Debug
  - Release

before_build:
  - git submodule update --init --recursive

  # Run Cmake
  - cmake External\GLFW\ -B External\GLFW\Win32\ -G "Visual Studio 15 2017 Win64" 
  - cmake External\Diligent\ -B External\Diligent\gen\ -G "Visual Studio 15 2017 Win64" 
  - cmake External\Assimp\ -B External\Assimp\build\ -G "Visual Studio 15 2017 Win64" 

  #Build Deps
  - ps: msbuild External\GLFW\Win32\GLFW.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
  - ps: msbuild External\Diligent\gen\Project.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
  - ps: msbuild External\Assimp\build\Assimp.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" 
 
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Nuclear Project.sln