image: Visual Studio 2017
platform:
  - X64

configuration:
  - Debug
  - Release

before_build:
  - git clone https://github.com/Zone-organization/Nuclear-Deps.git ..\Nuclear-Deps
  - ps: msbuild ..\Nuclear-Deps\Nuclear-Deps.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - git clone https://github.com/Zone-organization/LLGL.git
  - cmake -G "Visual Studio 15 2017" -LLGL_BUILD_RENDERER_DIRECT3D11 -LLGL_BUILD_RENDERER_DIRECT3D12 -LLGL_BUILD_RENDERER_OPENGL

  build:
  parallel: true                  # enable MSBuild parallel builds
  project: Nuclear Project.sln