image: Visual Studio 2017
platform:
  - x86
#  - X64

configuration:
  - Debug
  - Release

before_build:
git clone https://github.com/Zone-organization/Nuclear-Deps.git ..\Nuclear-Deps
msbuild ..\Nuclear-Deps\Nuclear-Deps.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Nuclear Project.sln