image: Visual Studio 2017
platform:
  - X64

configuration:
  - Debug
  - Release

before_build:
  - git clone https://github.com/Zone-organization/Nuclear-Deps.git ..\Nuclear-Deps
  - ps: msbuild ..\Nuclear-Deps\Nuclear-Deps.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - git clone https://github.com/Zone-organization/LLGL.git ..\LLGL
  - ps: tree
  - ps: tree ..
  - ps: tree ..\LLGL
  - cmake -S "..\LLGL" -B "..\LLGL\Projects" -G "Visual Studio 15 2017 Win64"
  - ps: msbuild ..\LLGL\Projects\LLGL.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
build:
  parallel: true                  # enable MSBuild parallel builds
  project: Nuclear Project.sln