image: Visual Studio 2017
platform:
  - X64

configuration:
  - Debug
  - Release

before_build:
  - git clone https://github.com/Zone-organization/LLGL.git ..\LLGL
  - cd ..\LLGL\
  - cmake --help
  - ps: msbuild Projects\LLGL.sln /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
  - cd ..\nuclear-engine\
  - git clone https://github.com/Zone-organization/Nuclear-Deps.git ..\Nuclear-Deps
  - ps: msbuild ..\Nuclear-Deps\Nuclear-Deps.sln /m /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

build:
  parallel: true                  # enable MSBuild parallel builds
  project: Nuclear Project.sln