<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <OutputPath>..\Bin\$(Configuration)X64\</OutputPath>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AssemblyName>Nuclear.Managed</AssemblyName>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Source\AssemblyLoader.cs" />
    <Compile Include="Source\ExtensionMethods.cs" />
    <Compile Include="Source\GarbageCollector.cs" />
    <Compile Include="Source\InternalCalls.cs" />
    <Compile Include="Source\InteropTypes.cs" />
    <Compile Include="Source\ManagedHost.cs" />
    <Compile Include="Source\ManagedObject.cs" />
    <Compile Include="Source\Marshalling.cs" />
    <Compile Include="Source\MSBuildRunner.cs" />
    <Compile Include="Source\NativeLogger.cs" />
    <Compile Include="Source\TypeInterface.cs" />
    <Compile Include="Source\TypeNotFoundException.cs" />
    <Compile Include="Source\UniqueList.cs" />
  </ItemGroup>
</Project>
